"""add content generation engine

Revision ID: 0917dd1bdfb9
Revises: fb5c7dd0a91d
Create Date: 2026-08-07 08:15:21.996024
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0917dd1bdfb9'
down_revision: Union[str, None] = 'fb5c7dd0a91d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('facebook', 'instagram', 'threads', 'linkedin', 'x', 'google_business', name='content_platform'), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('objective', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending', 'completed', 'failed', name='content_status'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('generated_content', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_generations_brand_id'), 'content_generations', ['brand_id'], unique=False)
    op.create_index(op.f('ix_content_generations_user_id'), 'content_generations', ['user_id'], unique=False)
    op.create_index(op.f('ix_content_generations_workspace_id'), 'content_generations', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_generations_workspace_id'), table_name='content_generations')
    op.drop_index(op.f('ix_content_generations_user_id'), table_name='content_generations')
    op.drop_index(op.f('ix_content_generations_brand_id'), table_name='content_generations')
    op.drop_table('content_generations')
    # ### end Alembic commands ###
