"""add encrypted oauth token fields

Revision ID: 2e7e665d1446
Revises: db5694b707bd
Create Date: 2026-08-07 13:33:10.207280
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2e7e665d1446'
down_revision: Union[str, None] = 'db5694b707bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('access_token_ciphertext', sa.Text(), nullable=True))
    op.add_column('social_accounts', sa.Column('refresh_token_ciphertext', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_accounts', 'refresh_token_ciphertext')
    op.drop_column('social_accounts', 'access_token_ciphertext')
    # ### end Alembic commands ###
