"""create social accounts

Revision ID: db5694b707bd
Revises: 32af27b96513
Create Date: 2026-08-07 13:06:03.775822
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'db5694b707bd'
down_revision: Union[str, None] = '32af27b96513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.Enum('instagram', 'facebook', 'threads', 'linkedin', 'x', name='social_platform'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'connected', 'expired', 'revoked', 'error', name='social_account_status'), nullable=False),
    sa.Column('platform_account_id', sa.String(length=255), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'platform', 'platform_account_id', name='uq_social_accounts_workspace_platform_account')
    )
    op.create_index(op.f('ix_social_accounts_brand_id'), 'social_accounts', ['brand_id'], unique=False)
    op.create_index(op.f('ix_social_accounts_workspace_id'), 'social_accounts', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_accounts_workspace_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_brand_id'), table_name='social_accounts')
    op.drop_table('social_accounts')
    # ### end Alembic commands ###
