"""add ai credit accounting

Revision ID: e291e60ea32a
Revises: 0917dd1bdfb9
Create Date: 2026-08-07 09:31:01.673148
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e291e60ea32a'
down_revision: Union[str, None] = '0917dd1bdfb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_credit_accounts',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('lifetime_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('ai_credit_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('generation_id', sa.UUID(), nullable=True),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('actual_cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['content_generations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_credit_ledger_generation_id'), 'ai_credit_ledger', ['generation_id'], unique=False)
    op.create_index(op.f('ix_ai_credit_ledger_workspace_id'), 'ai_credit_ledger', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_credit_ledger_workspace_id'), table_name='ai_credit_ledger')
    op.drop_index(op.f('ix_ai_credit_ledger_generation_id'), table_name='ai_credit_ledger')
    op.drop_table('ai_credit_ledger')
    op.drop_table('workspace_credit_accounts')
    # ### end Alembic commands ###
