"""add brand brain fields

Revision ID: fb5c7dd0a91d
Revises: c86dd88451d5
Create Date: 2026-08-07 07:54:05.936599
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb5c7dd0a91d'
down_revision: Union[str, None] = 'c86dd88451d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('target_audience', sa.Text(), nullable=True))
    op.add_column('brands', sa.Column('brand_voice', sa.Text(), nullable=True))
    op.add_column('brands', sa.Column('value_proposition', sa.Text(), nullable=True))
    op.add_column('brands', sa.Column('products_services', sa.Text(), nullable=True))
    op.add_column('brands', sa.Column('keywords', sa.Text(), nullable=True))
    op.add_column('brands', sa.Column('forbidden_words', sa.Text(), nullable=True))
    op.add_column('brands', sa.Column('default_cta', sa.Text(), nullable=True))
    op.add_column(
        'brands',
        sa.Column(
            'language',
            sa.String(length=20),
            nullable=False,
            server_default='zh-TW',
        ),
    )
    op.alter_column(
        'brands',
        'language',
        server_default=None,
    )
    op.add_column('brands', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('brands', sa.Column('brand_guidelines', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'brand_guidelines')
    op.drop_column('brands', 'country')
    op.drop_column('brands', 'language')
    op.drop_column('brands', 'default_cta')
    op.drop_column('brands', 'forbidden_words')
    op.drop_column('brands', 'keywords')
    op.drop_column('brands', 'products_services')
    op.drop_column('brands', 'value_proposition')
    op.drop_column('brands', 'brand_voice')
    op.drop_column('brands', 'target_audience')
    # ### end Alembic commands ###
